# config

gitignore: false

test-cmd: /usr/bin/make test
## Run tests, fix problems found and then exit
#test: false

lint-cmd: go fmt

auto-commits: false

read: AGENTS.md
# model: gemini/gemini-2.5-flash-lite-preview-06-17
# weak_model: gemini/gemini-2.5-flash-lite-preview-06-17
# editor_model: openai/gpt-5
