Initial Events -> Start Stack
Start Stack -> Current Player
Current Player -> Pass Priority
Pass Priority -> NonCurrent Player
NonCurrent Player -> Pass Priority
Current Player -> Add Stack
NonCurrent Player -> Add Stack
Add Stack -> Current Player
Add Stack -> NonCurrent Player
Pass Priority -> Resolve Stack
Resolve Stack -> Cleanup
