name = "Arzakon"
main_cards = [
["2",	"Hurr Jackal"],
["6",	"Forest"],
["6",	"Mountain"],
["1",	"Mox Emerald"],
["1",	"Mox Jet"],
["1",	"Mox Pearl"],
["1",	"Mox Ruby"],
["1",	"Mox Sapphire"],
["6",	"Swamp"],
["6",	"Plains"],
["6",	"Island"],
["4",	"Gem Bazaar"],
["2",	"Elvish Archers"],
["2",	"Erg Raiders"],
["2",	"Grizzly Bears"],
["2",	"Mesa Pegasus"],
["2",	"Pikemen"],
["2",	"Samite Healer"],
["2",	"Savannah Lions"],
["2",	"Will-O'-The-Wisp"],
["2",	"Zephyr Falcon"],
["2",	"Wall of Dust"],
["1",	"Ancestral Recall"],
["1",	"Berserk"],
["1",	"Regrowth"],
["1",	"Time Walk"],
["1",	"Timetwister"],
["1",	"Wheel of Fortune"],
["1",	"Sol Ring"],
["1",	"Braingeyser"],
["2",	"Animate Dead"],
["2",	"Blood Lust"],
["1",	"Circle of Protection: Artifacts"],
["1",	"Circle of Protection: Black"],
["1",	"Circle of Protection: Blue"],
["1",	"Circle of Protection: Green"],
["1",	"Circle of Protection: Red"],
["1",	"Circle of Protection: White"],
["2",	"Desert Twister"],
["2",	"Disintegrate"],
["2",	"Fog"],
["2",	"Giant Growth"],
["2",	"Giant Strength"],
["2",	"Howl from Beyond"],
["2",	"Immolation"],
["2",	"Lightning Bolt"],
["1",	"Mind Twist"],
["2",	"Paralyze"],
["2",	"Power Sink"],
["2",	"Pyrotechnics"],
["2",	"Raise Dead"],
["2",	"Siren's Call"],
["2",	"Spirit Link"],
["4",	"Mishra's Factory"],
["1",	"Aladdin's Ring"],
["1",	"Black Mana Battery"],
["1",	"Blue Mana Battery"],
["2",	"Brass Man"],
["1",	"Clockwork Avian"],
["1",	"Clockwork Beast"],
["1",	"Colossus of Sardia"],
["1",	"Dancing Scimitar"],
["1",	"Diabolic Machine"],
["4",	"Fellwar Stone"],
["1",	"Green Mana Battery"],
["1",	"Grapeshot Catapult"],
["1",	"Obsianus Golem"],
["1",	"Shapeshifter"],
["1",	"Tetravus"],
["2",	"The Hive"],
["1",	"Triskelion"],
["1",	"Urza's Avenger"],
["1",	"White Mana Battery"],
["1",	"Red Mana Battery"],
["1",	"Mishra's Workshop"],
]
sideboard_cards = [
]
face = "MPS_Arzakon.png"
