name = "Crag Hydra"
main_cards = [
["22",	"Mountain"],
["4",	"Manaflare"],
["4",	"Power Surge"],
["4",	"Fireball"],
["2",	"Lightning Bolt"],
["4",	"Inferno"],
["4",	"Onulet"],
["4",	"Wall of Fire"],
["4",	"Disintegrate"],
["1",	"Detonate"],
["2",	"Soul Net"],
["2",	"Shivan Dragon"],
]
sideboard_cards = [
["3",	"The Hive"],
["1",	"Red Elemental Blast"],
]
walking_sprite = "R_Wrm.spr.png"
walking_shadow_sprite = "Swrm.spr.png"
face = "MPS_Crag_Hydra.png"
