name = "Dracur"
main_cards = [
["5",	"Mountain"],
["5",	"Swamp"],
["5",	"Forest"],
["3",	"Gem Bazaar"],
["1",	"Mox Emerald"],
["1",	"Mox Jet"],
["1",	"Mox Ruby"],
["1",	"Black Lotus"],
["2",	"Strip Mine"],
["2",	"Fellwar Stone"],
["4",	"Stone Rain"],
["2",	"Dingus Egg"],
["2",	"Fireball"],
["2",	"Disintegrate"],
["2",	"Lightning Bolt"],
["2",	"Manaflare"],
["2",	"Blight"],
["2",	"Desert Twister"],
["3",	"Fissure"],
["1",	"Mind Twist"],
["2",	"Ragman"],
["4",	"Hypnotic Specter"],
["2",	"Disrupting Scepter"],
["3",	"Wall of Dust"],
]
sideboard_cards = [
["2",	"Tranquility"],
["2",	"Earthquake"],
["1",	"Tsunami"],
["2",	"Stream of Life"],
["1",	"Gloom"],
]
