name = "Goblin Warlord"
main_cards = [
["21",	"Mountain"],
["4",	"Orcish Oriflamme"],
["4",	"Helm of Chatzuk"],
["4",	"Goblin King"],
["4",	"Goblin Balloon Brigade"],
["4",	"Mons Goblin Raiders"],
["4",	"Keldon Warlord"],
["4",	"Goblin Polka Band"],
["2",	"Tawnos' Weaponry"],
["2",	"Immolation"],
["4",	"Giant Strength"],
]
sideboard_cards = [
["2",	"Manabarbs"],
["1",	"Shatter"],
["1",	"Red Elemental Blast"],
["2",	"Goblin Rock Sled"],
["1",	"Sunglasses of Urza"],
]
walking_sprite = "R_Lrd.spr.png"
walking_shadow_sprite = "Sr_Lrd.spr.png"
face = "MPS_Goblin_Warlord.png"
