name = "Mind Stealer"
main_cards = [
["11",	"Swamp"],
["11",	"Island"],
["3",	"Hypnotic Specter"],
["4",	"Sengir Vampire"],
["3",	"Will-o'-the-Wisp"],
["4",	"Control Magic"],
["2",	"Steal Artifact"],
["4",	"Unholy Strength"],
["2",	"Siren's Call"],
["1",	"Mind Twist"],
["2",	"Phantasmal Forces"],
["2",	"Phantom Monster"],
["2",	"Drain Power"],
["2",	"Fellwar Stone"],
["2",	"Junún Efreet"],
["2",	"Animate Dead"],
["2",	"Call from the Grave"],
]
sideboard_cards = [
["3",	"Sindbad"],
["1",	"Lifetap"],
["1",	"Deathgrip"],
["1",	"Volcanic Eruption"],
["1",	"Gloom"],
]
walking_sprite = "M_Lrd.spr.png"
walking_shadow_sprite = "Sm_Lrd.spr.png"
face = "MPS_Mind_Stealer.png"
