name = "Paladin"
main_cards = [
["18",	"Plains"],
["6",	"Island"],
["4",	"Northern Paladin"],
["4",	"White Knight"],
["2",	"Benalish Hero"],
["4",	"Holy Strength"],
["1",	"Disenchant"],
["2",	"Red Ward"],
["4",	"Angry Mob"],
["2",	"Sleight of Mind"],
["2",	"Magical Hack"],
["3",	"Karma"],
["2",	"Circle of Protection Black"],
["1",	"Swords to Plowshares"],
["2",	"Segovian Leviathan"],
]
sideboard_cards = [
["1",	"Magical Hack"],
["2",	"Sleight of Mind"],
["1",	"Swords to Plowshares"],
["2",	"Divine Transformation"],
]
walking_sprite = "W_Lrd.spr.png"
walking_shadow_sprite = "Sw_Lrd.spr.png"
face = "MPS_Paladin.png"
