name = "Queltosh"
main_cards = [
["8",	"Island"],
["8",	"Plains"],
["8",	"Mountain"],
["1",	"Eye for an Eye"],
["1",	"Pikemen"],
["1",	"Mesa Pegasus"],
["1",	"Serra Angel"],
["1",	"Spirit Link"],
["1",	"White Knight"],
["1",	"Ancestral Recall"],
["1",	"Control Magic"],
["1",	"Giant Tortoise"],
["1",	"Mahamoti Djinn"],
["1",	"Prodigal Sorcerer"],
["1",	"Time Elemental"],
["1",	"Unstable Mutation"],
["1",	"Black Vise"],
["1",	"Candelabra of Tawnos"],
["1",	"Clockwork Avian"],
["1",	"Urza's Avenger"],
["1",	"Wall of Dust"],
["1",	"Feedback"],
["1",	"Fireball"],
["1",	"Land Tax"],
["1",	"Lightning Bolt"],
["1",	"Disenchant"],
["1",	"Zephyr Falcon"],
["1",	"Counterspell"],
["1",	"Power Sink"],
["1",	"Spell Blast"],
["1",	"Brass Man"],
["1",	"Wall of Air"],
["1",	"Phantasmal Forces"],
["1",	"Fire Elemental"],
["1",	"Phantom Monster"],
["1",	"The Hive"],
]
sideboard_cards = [
["1",	"Reverse Damage"],
["1",	"Divine Transformation"],
["1",	"Pearled Unicorn"],
["1",	"Angry Mob"],
["1",	"Karma"],
["1",	"Northern Paladin"],
["1",	"Magnetic Mountain"],
["1",	"Red Elemental Blast"],
["1",	"Crystal Rod"],
["1",	"Lifetap"],
["1",	"Wooden Sphere"],
["1",	"Blue Elemental Blast"],
["1",	"Burrowing"],
["1",	"Circle of Protection Red"],
["1",	"Ivory Cup"],
["1",	"Flashfires"],
["1",	"Disenchant"],
]
