name = "Sainted One"
main_cards = [
["22",	"Plains"],
["1",	"Mox Pearl"],
["1",	"Sol Ring"],
["1",	"Black Lotus"],
["1",	"Mishra's Workshop"],
["2",	"White Mana Battery"],
["2",	"Serra Angel"],
["2",	"Personal Incarnation"],
["3",	"White Knight"],
["3",	"Knights of the Rainbow Vale"],
["2",	"Blessing"],
["1",	"Balance"],
["3",	"Dingus Egg"],
["4",	"Circle of Protection from Artifacts"],
["3",	"Armageddon Clock"],
["3",	"Bottle of Suleiman"],
["3",	"Armageddon"],
]
sideboard_cards = [
["2",	"Swords to Plowshares"],
["2",	"Disenchant"],
["1",	"Karma"],
["1",	"Circle of Protection Black"],
["1",	"Angry Mob"],
["2",	"Circle of Protection Blue"],
["2",	"Circle of Protection Green"],
["2",	"Circle of Protection Red"],
["1",	"Conversion"],
["3",	"Circle of Protection White"],
]
