name = "Summoner"
main_cards = [
["20",	"Forest"],
["4",	"Plains"],
["2",	"Colossus of Sardia"],
["4",	"Birds of Paradise"],
["4",	"Lifelace"],
["1",	"Channel"],
["3",	"Circle of Protection Green"],
["4",	"Hurricane"],
["4",	"War Mammoth"],
["3",	"Force of Nature"],
["2",	"Disenchant"],
["2",	"Healing Salve"],
["4",	"Radjan Spirit"],
]
sideboard_cards = [
["3",	"Giant Growth"],
["1",	"Lifeforce"],
["1",	"Tsunami"],
["1",	"Disenchant"],
]
