name = "Undead Knight"
main_cards = [
["22",	"Swamp"],
["3",	"Howl from Beyond"],
["3",	"Unholy Strength"],
["4",	"Bad Moon"],
["2",	"Flying Carpet"],
["4",	"Black Knight"],
["2",	"Drudge Skeletons"],
["2",	"Scathe Zombies"],
["2",	"Frozen Shade"],
["2",	"Fear"],
["2",	"Spirit Shackle"],
["2",	"Lost Soul"],
["3",	"El-Hajjaj"],
["2",	"Marsh Gas"],
["2",	"Nightmare"],
]
sideboard_cards = [
["3",	"Terror"],
["3",	"Bog Wraith"],
["3",	"Animate Dead"],
["3",	"Simulacrum"],
["2",	"Brass Man"],
["1",	"Obsianus Golem"],
]
walking_sprite = "Bk_Kht.spr.png"
walking_shadow_sprite = "Skht.spr.png"
face = "MPS_Undead_Knight.png"
