#!/usr/bin/env python3
"""Extract card names and tiers from a saved TierMaker HTML page.

Emits the full tier list to TOML. Card names are best-effort reconstructions
from the tiermaker image filenames (lowercase, hyphen-separated), so cards
with apostrophes, accents, or unusual capitalization will need to be fixed
manually when the corresponding set is added to the game.

Usage:
    python3 utils/extract_tiers.py \\
        "MtG Old School 93_94 (Eternal Central rules) - TierMaker.html" \\
        assets/configs/card_tiers.toml
"""

import re
import sys
from pathlib import Path


# TOML keys are derived from tier labels.
TIER_KEY_OVERRIDES = {
    "Played in most decks of their colors": "played_in_most_decks",
    "Played in specific archetypes only": "played_in_specific_archetypes",
}

# Words kept lowercase in the middle of a card name (MTG title-case convention).
SMALL_WORDS = {
    "a", "an", "and", "at", "by", "for", "from", "in", "of",
    "on", "or", "the", "to", "vs", "with",
}


def filename_to_card_name(filename: str) -> str:
    """Turn a tiermaker filename into a best-effort MTG card name.

    Examples:
        black-lotusjpg.png -> Black Lotus
        library-of-alexandriajpg.png -> Library of Alexandria
        zzzzz-1674965038strip-mine-1jpg.png -> Strip Mine
        mishras-factory-4jpg.png -> Mishras Factory
    """
    name = filename.rsplit(".", 1)[0]
    name = re.sub(r"jpg$", "", name)
    name = re.sub(r"^zzzzz-\d+", "", name)
    name = re.sub(r"-\d+$", "", name)

    words = name.split("-")
    titled: list[str] = []
    for i, word in enumerate(words):
        if not word:
            continue
        if 0 < i < len(words) - 1 and word in SMALL_WORDS:
            titled.append(word)
        else:
            titled.append(word[:1].upper() + word[1:])
    return " ".join(titled)


def tier_to_toml_key(tier_name: str) -> str:
    if tier_name in TIER_KEY_OVERRIDES:
        return TIER_KEY_OVERRIDES[tier_name]
    return re.sub(r"[^a-z0-9]+", "_", tier_name.lower()).strip("_")


def extract_tiers(html_path: Path) -> list[tuple[str, list[str]]]:
    html = html_path.read_text()
    tiers: list[tuple[str, list[str]]] = []
    for tier_match in re.finditer(
        r'<div class="tier-row">(.*?)</div><div class="settings-control"',
        html,
        re.DOTALL,
    ):
        block = tier_match.group(1)
        label_match = re.search(r'<span class="label">(.*?)</span>', block)
        if not label_match:
            continue
        tier_name = label_match.group(1)
        cards: list[str] = []
        for m in re.finditer(
            r"background-image: url\(&quot;[^&]*?/([^/&]+?)&quot;\)", block
        ):
            cards.append(filename_to_card_name(m.group(1)))
        tiers.append((tier_name, cards))
    return tiers


def write_toml(tiers: list[tuple[str, list[str]]], output_path: Path) -> None:
    lines = [
        "# Card power tiers for Old School 93/94 (Eternal Central rules).",
        "# Source: https://tiermaker.com/list/mtg/mtg-old-school-93-94-cards---eternal-central-banlist-15576465",
        "# Generated by utils/extract_tiers.py from a saved tiermaker page.",
        "#",
        "# Contains every card from the tier list, even if the game doesn't",
        "# load it yet. card_tiers.go silently drops entries that don't resolve",
        "# to a card in the current database, so new sets can be wired up by",
        "# simply adding the card data without touching this file. Names with",
        "# apostrophes, accents, or unusual capitalization may need manual",
        "# correction when the corresponding card is added.",
        "",
    ]
    for tier_name, cards in tiers:
        key = tier_to_toml_key(tier_name)
        lines.append(f"# {tier_name}")
        lines.append(f"{key} = [")
        for card in cards:
            escaped = card.replace('"', '\\"')
            lines.append(f'  "{escaped}",')
        lines.append("]")
        lines.append("")
    output_path.write_text("\n".join(lines))


def main() -> None:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <tiermaker.html> <output.toml>")
        sys.exit(1)

    html_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    tiers = extract_tiers(html_path)
    total = 0
    for tier_name, cards in tiers:
        print(f"  {tier_name}: {len(cards)} cards")
        total += len(cards)
    print(f"  total: {total}")

    write_toml(tiers, output_path)
    print(f"\nWrote {output_path}")


if __name__ == "__main__":
    main()
