s = [
  "Ancestral Recall",
  "Balance",
  "Black Lotus",
  "Braingeyser",
  "Chaos Orb",
  "Contract from Below",
  "Copy Artifact",
  "Demonic Tutor",
  "Library of Alexandria",
  "Mana Crypt",
  "Mind Twist",
  "Mishra's Workshop",
  "Mox Emerald",
  "Mox Jet",
  "Mox Pearl",
  "Mox Ruby",
  "Mox Sapphire",
  "Sol Ring",
  "Time Walk",
]

a = [
  "Armageddon",
  "Badlands",
  "Bayou",
  "Birds of Paradise",
  "Blue Elemental Blast",
  "Chain Lightning",
  "City of Brass",
  "Control Magic",
  "Counterspell",
  "Dark Ritual",
  "Disenchant",
  "Energy Flux",
  "Fireball",
  "Hymn to Tourach",
  "Juzám Djinn",
  "Land Tax",
  "Lightning Bolt",
  "Llanowar Elves",
  "Mana Drain",
  "Mana Vault",
  "Mishra's Factory",
  "Plateau",
  "Power Artifact",
  "Red Elemental Blast",
  "Regrowth",
  "Savannah",
  "Savannah Lions",
  "Scrubland",
  "Serendib Efreet",
  "Serra Angel",
  "Shatter",
  "Strip Mine",
  "Su-Chi",
  "Swords to Plowshares",
  "Sylvan Library",
  "Taiga",
  "Timetwister",
  "Tropical Island",
  "Tundra",
  "Underground Sea",
  "Volcanic Island",
  "Wheel of Fortune",
  "Wrath of God",
]

b = [
  "Amnesia",
  "Animate Dead",
  "Argothian Pixies",
  "Atog",
  "Ball Lightning",
  "Berserk",
  "Black Knight",
  "Black Vise",
  "Blood Moon",
  "Crumble",
  "Crusade",
  "Disrupting Scepter",
  "Divine Offering",
  "Dust to Dust",
  "Earthquake",
  "Elves of Deep Shadow",
  "Erhnam Djinn",
  "Fellwar Stone",
  "Flying Men",
  "Hammerheim",
  "Holy Light",
  "Hypnotic Specter",
  "Icatian Javelineers",
  "Ivory Tower",
  "Jayemdae Tome",
  "Juggernaut",
  "Kird Ape",
  "Mahamoti Djinn",
  "Maze of Ith",
  "Mirror Universe",
  "Moat",
  "Nevinyrral's Disk",
  "Old Man of the Sea",
  "Order of Leitbur",
  "Order of the Ebon Hand",
  "Pendelhaven",
  "Phantom Monster",
  "Psionic Blast",
  "Psychic Purge",
  "Recall",
  "Royal Assassin",
  "Scavenger Folk",
  "Sedge Troll",
  "Sengir Vampire",
  "Shivan Dragon",
  "Sinkhole",
  "Solkanar the Swamp King",
  "Stone Calendar",
  "Tetravus",
  "The Abyss",
  "The Rack",
  "Thunder Spirit",
  "Tranquility",
  "Triskelion",
  "Tundra Wolves",
  "Underworld Dreams",
  "Urborg",
  "Whirling Dervish",
  "White Knight",
  "Winter Orb",
]

c = [
  "Aeolipile",
  "Ankh of Mishra",
  "Army of Allah",
  "Ashes to Ashes",
  "Avoid Fate",
  "Azure Drake",
  "Bad Moon",
  "Benalish Hero",
  "Blood Lust",
  "Bog Rats",
  "Boomerang",
  "Brassclaw Orcs",
  "Chains of Mephistopheles",
  "Channel",
  "Circle of Protection: Artifacts",
  "Circle of Protection: Black",
  "Circle of Protection: Blue",
  "Circle of Protection: Green",
  "Circle of Protection: Red",
  "Circle of Protection: White",
  "Citanul Druid",
  "Clergy of the Holy Nimbus",
  "Clockwork Avian",
  "Clone",
  "Concordant Crossroads",
  "Copper Tablet",
  "Cuombajj Witches",
  "Dark Heart of the Wood",
  "Derelor",
  "Drain Life",
  "Drop of Honey",
  "Drudge Skeletons",
  "Elvish Archers",
  "Fallen Angel",
  "Fastbond",
  "Feldon's Cane",
  "Fork",
  "Gaeas Touch",
  "Gauntlet of Might",
  "Giant Growth",
  "Gloom",
  "Goblin Digging Team",
  "Goblin Hero",
  "Goblins of the Flarg",
  "Granite Gargoyle",
  "Greater Realm of Preservation",
  "Greed",
  "Guardian Beast",
  "Haunting Wind",
  "Hurkyl's Recall",
  "Hurricane",
  "Ice Storm",
  "Icy Manipulator",
  "In the Eye of Chaos",
  "Initiates of the Ebon Hand",
  "Instill Energy",
  "Ironclaw Orcs",
  "Jade Statue",
  "Mana Short",
  "Martyr's Cry",
  "Meekstone",
  "Mesa Pegasus",
  "Millstone",
  "Nether Void",
  "Oubliette",
  "Paralyze",
  "Pestilence",
  "Power Sink",
  "Repentant Blacksmith",
  "Reset",
  "Riptide",
  "Roc of Kher Ridges",
  "Safe Haven",
  "Sage of Lat-Nam",
  "Savaen Elves",
  "Scarwood Goblins",
  "Scryb Sprites",
  "Serendib Djinn",
  "Shatterstorm",
  "Spell Blast",
  "Spirit Link",
  "Standing Stones",
  "Stone Rain",
  "Stone-Throwing Devils",
  "Storm Seeker",
  "Storm World",
  "Tangle Kelp",
  "Tawnos's Coffin",
  "Terror",
  "The Tabernacle at Pendrell Vale",
  "Titania's Song",
  "Tivadar's Crusade",
  "Unstable Mutation",
  "Unsummon",
  "Uthden Troll",
  "Vesuvan Doppelganger",
  "Walking Dead",
  "Water Wurm",
  "Wild Growth",
  "Will-o'-the-Wisp",
  "Winds of Change",
  "Ydwen Efreet",
]

d = [
  "All Hallows Eve",
  "Ashnod's Altar",
  "Basalt Monolith",
  "Bazaar of Baghdad",
  "Blood of the Martyr",
  "Bone Flute",
  "Book of Rass",
  "Candelabra of Tawnos",
  "City of Shadows",
  "Cleansing",
  "Coal Golem",
  "Dance of Many",
  "Dark Sphere",
  "Deep Spawn",
  "Deep Water",
  "Diamond Valley",
  "Drowned",
  "Electric Eel",
  "Erg Raiders",
  "Eternal Flame",
  "Eureka",
  "Fasting",
  "Festival",
  "Fire Drake",
  "Firestorm Phoenix",
  "Fountain of Youth",
  "Frankenstein's Monster",
  "Gaea's Touch",
  "Goblin Artisans",
  "Goblin Balloon Brigade",
  "Goblin Caves",
  "Goblin Grenade",
  "Goblin King",
  "Goblin Shrine",
  "Goblin Wizard",
  "High Tide",
  "Homarid Spawning Bed",
  "Howling Mine",
  "Inquisition",
  "Killer Bees",
  "Kismet",
  "Knights of Thorn",
  "Lands Edge",
  "Library of Leng",
  "Living Armor",
  "Lord of Atlantis",
  "Lord of the Pit",
  "Lurker",
  "Mana Flare",
  "Mana Vortex",
  "Marsh Goblins",
  "Merfolk Assassin",
  "Merfolk of the Pearl Trident",
  "Mijae Djinn",
  "Miracle Worker",
  "Mons's Goblin Raiders",
  "Necropolis",
  "Niall Silvain",
  "Nicol Bolas",
  "Nova Pentacle",
  "Orc General",
  "Palladia Mors",
  "People of the Woods",
  "Preacher",
  "Psychic Allergy",
  "Rainbow Vale",
  "Rasputin Dreamweaver",
  "Reconstruction",
  "Resurrection",
  "River Merfolk",
  "Rocket Launcher",
  "Rukh Egg",
  "Runesword",
  "Sacrifice",
  "Scarwood Bandits",
  "Season of the Witch",
  "Sorrow's Path",
  "Soul Exchange",
  "Spitting Slug",
  "Squire",
  "Stasis",
  "Stream of Life",
  "Sunken City",
  "Time Elemental",
  "Time Vault",
  "Tormod's Crypt",
  "Tower of Coireall",
  "Transmute Artifact",
  "Twiddle",
  "Vaevictis Asmadi",
  "Verduran Enchantress",
  "Vodalian Knights",
  "Vodalian Soldiers",
]

f = [
  "Abomination",
  "Abu Ja'far",
  "Acid Rain",
  "Adun Oakenshield",
  "Air Elemental",
  "Alabaster Potion",
  "Aladdin",
  "Aladdin's Lamp",
  "Aladdin's Ring",
  "Ali Baba",
  "Ali from Cairo",
  "Amrou Kithkin",
  "Amulet of Kroog",
  "Angry Mob",
  "Angus Mackenzie",
  "Animate Artifact",
  "Animate Wall",
  "Apprentice Wizard",
  "Arboria",
  "Arena",
  "Argivian Archaeologist",
  "Argivian Blacksmith",
  "Argothian Treefolk",
  "Armageddon Clock",
  "Armor Thrull",
  "Artifact Blast",
  "Artifact Possession",
  "Artifact Ward",
  "Ashnod's Battle Gear",
  "Ashnod's Transmogrant",
  "Aspect of Wolf",
  "Aswan Jaguar",
  "Backfire",
  "Banshee",
  "Barl's Cage",
  "Bartel Runeaxe",
  "Basal Thrull",
  "Battering Ram",
  "Bird Maiden",
  "Black Mana Battery",
  "Black Ward",
  "Blaze of Glory",
  "Blessing",
  "Blight",
  "Blue Mana Battery",
  "Blue Ward",
  "Bog Imp",
  "Bog Wraith",
  "Bottle of Suleiman",
  "Brainwash",
  "Brass Man",
  "Breeding Pit",
  "Bronze Tablet",
  "Brothers of Fire",
  "Burrowing",
  "Call from the Grave",
  "Camel",
  "Camouflage",
  "Carnivorous Plant",
  "Carrion Ants",
  "Castle",
  "Cave People",
  "Celestial Prism",
  "Chaoslace",
  "City in a Bottle",
  "Clay Statue",
  "Cleanse",
  "Clockwork Beast",
  "Cockatrice",
  "Colossus of Sardia",
  "Conch Horn",
  "Consecrate Land",
  "Conservator",
  "Conversion",
  "Coral Helm",
  "Cosmic Horror",
  "Craw Wurm",
  "Creature Bond",
  "Crimson Kobolds",
  "Crimson Manticore",
  "Crookshank Kobolds",
  "Crystal Rod",
  "Curse Artifact",
  "Cursed Land",
  "Cursed Rack",
  "Cyclone",
  "Cyclopean Mummy",
  "Cyclopean Tomb",
  "Damping Field",
  "Dancing Scimitar",
  "Dandân",
  "Darkpact",
  "Death Ward",
  "Deathgrip",
  "Deathlace",
  "Demonic Attorney",
  "Demonic Hordes",
  "Desert",
  "Desert Nomads",
  "Desert Twister",
  "Detonate",
  "Diabolic Machine",
  "Dingus Egg",
  "Disintegrate",
  "Divine Intervention",
  "Divine Transformation",
  "Drafna's Restoration",
  "Dragon Engine",
  "Dragon Whelp",
  "Drain Power",
  "Durkwood Boars",
  "Dwarven Armorer",
  "Dwarven Demolition Team",
  "Dwarven Lieutenant",
  "Dwarven Ruins",
  "Dwarven Soldier",
  "Dwarven Warriors",
  "Dwarven Weaponsmith",
  "Earth Elemental",
  "Earthbind",
  "Eater of the Dead",
  "Ebon Praetor",
  "Ebon Stronghold",
  "Ebony Horse",
  "El-Hajjâj",
  "Elder Land Wurm",
  "Elder Spawn",
  "Elven Riders",
  "Elvish Scout",
  "Energy Tap",
  "Erosion",
  "Eternal Warrior",
  "Evil Presence",
  "Exorcist",
  "Eye for an Eye",
  "Faerie Dragon",
  "Falling Star",
  "False Orders",
  "Farmstead",
  "Fear",
  "Feedback",
  "Field of Dreams",
  "Fire and Brimstone",
  "Fire Elemental",
  "Firebreathing",
  "Fishliver Oil",
  "Fissure",
  "Flash Counter",
  "Flashfires",
  "Flight",
  "Flood",
  "Flying Carpet",
  "Fog",
  "Force of Nature",
  "Force Spike",
  "Forcefield",
  "Fortified Area",
  "Frozen Shade",
  "Fungusaur",
  "Gaea's Avenger",
  "Gaea's Liege",
  "Gaseous Form",
  "Gate to Phyrexia",
  "Ghazbán Ogre",
  "Ghost Ship",
  "Giant Badger",
  "Giant Shark",
  "Giant Spider",
  "Giant Strength",
  "Giant Tortoise",
  "Glasses of Urza",
  "Goblin Chirurgeon",
  "Goblin Polka Band",
  "Goblin Rock Sled",
  "Golgothian Sylex",
  "Grapeshot Catapult",
  "Grave Robbers",
  "Gravity Sphere",
  "Gray Ogre",
  "Green Mana Battery",
  "Green Ward",
  "Grizzly Bears",
  "Guardian Angel",
  "Gwendlyn Di Corci",
  "Halfdane",
  "Hasran Ogress",
  "Havenwood Battleground",
  "Hazezon Tamar",
  "Healing Salve",
  "Hellfire",
  "Helm of Chatzuk",
  "Hidden Path",
  "Hill Giant",
  "Holy Armor",
  "Holy Day",
  "Holy Strength",
  "Howl from Beyond",
  "Hurloon Minotaur",
  "Hurr Jackal",
  "Hyperion Blacksmith",
  "Icatian Lieutenant",
  "Ifh-Bíff Efreet",
  "Illusionary Mask",
  "Immolation",
  "Implements of Sacrifice",
  "Inferno",
  "Invisibility",
  "Iron Star",
  "Ironroot Treefolk",
  "Island Fish Jasconius",
  "Island Sanctuary",
  "Ivory Cup",
  "Jacques Le Vert",
  "Jade Monolith",
  "Jalum Tome",
  "Jandor's Ring",
  "Jandor's Saddlebags",
  "Jasmine Boreal",
  "Jeweled Bird",
  "Jihad",
  "Jovial Evil",
  "Jump",
  "Junún Efreet",
  "Karma",
  "Keepers of the Faith",
  "Keldon Warlord",
  "Khabál Ghoul",
  "King Suleiman",
  "Kobolds of Kher Keep",
  "Kormus Bell",
  "Kudzu",
  "Lance",
  "Land Leeches",
  "Leviathan",
  "Ley Druid",
  "Lich",
  "Lifeforce",
  "Lifelace",
  "Lifetap",
  "Living Artifact",
  "Living Lands",
  "Living Plane",
  "Living Wall",
  "Lost Soul",
  "Lure",
  "Magical Hack",
  "Magnetic Mountain",
  "Mana Clash",
  "Manabarbs",
  "Marsh Gas",
  "Marsh Viper",
  "Martyrs of Korlis",
  "Merchant Ship",
  "Metamorphosis",
  "Mightstone",
  "Mind Bomb",
  "Mindstab Thrull",
  "Mishra's War Machine",
  "Moorish Cavalry",
  "Morale",
  "Moss Monster",
  "Mountain Yeti",
  "Murk Dwellers",
  "Nafs Asp",
  "Nameless Race",
  "Natural Selection",
  "Necropolis of Azar",
  "Nether Shadow",
  "Nettling Imp",
  "Night Soil",
  "Nightmare",
  "Northern Paladin",
  "Obelisk of Undoing",
  "Obsianus Golem",
  "Onulet",
  "Orcish Artillery",
  "Orcish Catapult",
  "Orcish Mechanics",
  "Orcish Oriflamme",
  "Orgg",
  "Ornithopter",
  "Osai Vultures",
  "Pandora's Box",
  "Pearled Unicorn",
  "Personal Incarnation",
  "Petra Sphinx",
  "Phantasmal Forces",
  "Phantasmal Terrain",
  "Phyrexian Gremlins",
  "Piety",
  "Pikemen",
  "Pirate Ship",
  "Pit Scorpion",
  "Plague Rats",
  "Power Leak",
  "Power Struggle",
  "Power Surge",
  "Powerleech",
  "Pradesh Gypsies",
  "Priest of Yawgmoth",
  "Primal Clay",
  "Prismatic Dragon",
  "Prodigal Sorcerer",
  "Psionic Entity",
  "Psychic Venom",
  "Purelace",
  "Pyramids",
  "Pyrotechnics",
  "Radjan Spirit",
  "Rag Man",
  "Raging River",
  "Rainbow Knights",
  "Raise Dead",
  "Rakalite",
  "Rebirth",
  "Red Mana Battery",
  "Red Ward",
  "Reflecting Mirror",
  "Regeneration",
  "Reincarnation",
  "Relic Bind",
  "Remove Enchantments",
  "Remove Soul",
  "Reverse Damage",
  "Reverse Polarity",
  "Righteousness",
  "Ring of Ma'rûf",
  "Ring of Renewal",
  "Rock Hydra",
  "Rod of Ruin",
  "Rohgahh of Kher Keep",
  "Rubinia Soulsinger",
  "Ruins of Trokair",
  "Samite Healer",
  "Sandals of Abdallah",
  "Sandstorm",
  "Scarecrow",
  "Scarwood Hag",
  "Scathe Zombies",
  "Scavenging Ghoul",
  "Sea Serpent",
  "Seasinger",
  "Seeker",
  "Segovian Leviathan",
  "Sewers of Estark",
  "Shahrazad",
  "Shanodin Dryads",
  "Shapeshifter",
  "Simulacrum",
  "Sindbad",
  "Singing Tree",
  "Siren's Call",
  "Sisters of the Flame",
  "Skull of Orm",
  "Sleight of Mind",
  "Smoke",
  "Sorceress Queen",
  "Soul Net",
  "Spectral Cloak",
  "Spinal Villain",
  "Spirit Shackle",
  "Spore Cloud",
  "Staff of Zegon",
  "Stangg",
  "Steal Artifact",
  "Stone Giant",
  "Sunglasses of Urza",
  "Svyelunite Temple",
  "Sword of the Ages",
  "Tablet of Epityr",
  "Tawnos's Wand",
  "Tawnos's Weaponry",
  "Telekinesis",
  "Tempest Efreet",
  "Tetsuo Umezawa",
  "The Brute",
  "The Fallen",
  "The Hive",
  "Thelonite Druid",
  "Thicket Basilisk",
  "Thoughtlace",
  "Throne of Bone",
  "Thrull Retainer",
  "Timber Wolves",
  "Tivadars Crusade",
  "Tolaria",
  "Tormods Crypt",
  "Tracker",
  "Tsunami",
  "Tunnel",
  "Two-Headed Giant of Foriys",
  "Uncle Istvan",
  "Unholy Strength",
  "Untamed Wilds",
  "Urza's Avenger",
  "Urza's Chalice",
  "Urza's Mine",
  "Urza's Miter",
  "Urza's Power Plant",
  "Urza's Tower",
  "Vampire Bats",
  "Venom",
  "Veteran Bodyguard",
  "Visions",
  "Vodalian Mage",
  "Volcanic Eruption",
  "Wall of Air",
  "Wall of Bone",
  "Wall of Brambles",
  "Wall of Dust",
  "Wall of Fire",
  "Wall of Ice",
  "Wall of Spears",
  "Wall of Stone",
  "Wall of Swords",
  "Wall of Water",
  "Wall of Wood",
  "Wand of Ith",
  "Wanderlust",
  "War Barge",
  "War Elephant",
  "War Mammoth",
  "Warp Artifact",
  "Water Elemental",
  "Weakness",
  "Weakstone",
  "Web",
  "Whimsy",
  "Whippoorwill",
  "White Mana Battery",
  "White Ward",
  "Windseeker Centaur",
  "Winter Blast",
  "Witch Hunter",
  "Wooden Sphere",
  "Word of Binding",
  "Word of Command",
  "Worms of the Earth",
  "Wormwood Treefolk",
  "Wyluli Wolf",
  "Xenic Poltergeist",
  "Xira Arien",
  "Yawgmoth Demon",
  "Yotian Soldier",
  "Zephyr Falcon",
  "Zombie Master",
]

